---
apiVersion: v1
kind: Namespace
metadata:
  name: kubemate
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: kubemate-apps
  namespace: kubemate
spec:
  interval: 24h
  timeout: 60s
  url: https://github.com/mgoltzsche/kubemate-apps
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubemate-apps
  namespace: kubemate
spec:
  sourceRef:
    kind: GitRepository
    name: kubemate-apps
  path: ./apps
  interval: 24h
  timeout: 60s
  wait: false
  prune: true
