apiVersion: v1
kind: Namespace
metadata:
  name: kubemate
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubemate-apps
  namespace: kubemate
spec:
  interval: 24h
  path: ./apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubemate-apps
  timeout: 60s
  wait: false
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubemate-apps
  namespace: kubemate
spec:
  interval: 24h
  ref:
    branch: main
  timeout: 60s
  url: https://github.com/mgoltzsche/kubemate-apps
